const MentorCardContents = [
    // Organizer
    {
        id: 1,
        name: "Kak Malique",
        position: "Participants",
        image: "/images/id-card/ka malique.png",
        link: "https://www.instagram.com/kamalique/?hl=en",
        CategoryTeam: { name: "Chairman" },
    },
    {
        id: 2,
        name: "Fauzan",
        position: "Participants",
        image: "/images/id-card/fauzan.png",
        link: "#",
        CategoryTeam: { name: "Quality Control" },
    },
    {
        id: 3,
        name: "Alfi Syahri",
        position: "Participants",
        image: "/images/id-card/alfi syahri.png",
        link: "#",
        CategoryTeam: { name: "Organizer" },
    },
    {
        id: 4,
        name: "Andini",
        position: "Participants",
        image: "/images/id-card/andini.png",
        link: "#",
        CategoryTeam: { name: "Organizer" },
    },
    {
        id: 5,
        name: "Maulana",
        position: "Participants",
        image: "/images/id-card/maulana.png",
        link: "https://www.linkedin.com/in/maulanasykari",
        CategoryTeam: { name: "Organizer" },
    },
    {
        id: 6,
        name: "Nuni",
        position: "Participants",
        image: "/images/id-card/nuni.png",
        link: "#",
        CategoryTeam: { name: "Organizer" },
    },
    {
        id: 7,
        name: "Tsabit",
        position: "Participants",
        image: "/images/id-card/tsabit.png",
        link: "#",
        CategoryTeam: { name: "Organizer" },
    },
    // Participants
    {
        id: 8,
        name: "Ade Oktasari",
        position: "Participants",
        image: "/images/id-card/ade oktasari.png",
        link: "#",
        CategoryTeam: { name: "Participants" },
    },
    {
        id: 9,
        name: "Akhmad Fakhruddin",
        position: "Participants",
        image: "/images/id-card/akhmad fakhruddin.png",
        link: "#",
        CategoryTeam: { name: "Participants" },
    },
    {
        id: 10,
        name: "Bilqis Muthia Setiadi",
        position: "Participants",
        image: "/images/id-card/bilqis muthia setiadi.png",
        link: "#",
        CategoryTeam: { name: "Participants" },
    },
    {
        id: 11,
        name: "Devi Oktariza",
        position: "Participants",
        image: "/images/id-card/devi oktariza.png",
        link: "#",
        CategoryTeam: { name: "Participants" },
    },
    {
        id: 12,
        name: "Dwi Fitriyani",
        position: "Participants",
        image: "/images/id-card/dwi fitriyani.png",
        link: "#",
        CategoryTeam: { name: "Participants" },
    },
    {
        id: 13,
        name: "Eti Dwi Riani",
        position: "Participants",
        image: "/images/id-card/eti dwi riani.png",
        link: "#",
        CategoryTeam: { name: "Participants" },
    },
    {
        id: 14,
        name: "Fajar Ramadhan",
        position: "Participants",
        image: "/images/id-card/fajar ramadhan.png",
        link: "#",
        CategoryTeam: { name: "Participants" },
    },
    {
        id: 15,
        name: "Faridamiaty",
        position: "Participants",
        image: "/images/id-card/faridamiaty.png",
        link: "#",
        CategoryTeam: { name: "Participants" },
    },
    {
        id: 16,
        name: "Fathi Ahmad",
        position: "Participants",
        image: "/images/id-card/fathi ahmad.png",
        link: "#",
        CategoryTeam: { name: "Participants" },
    },
    {
        id: 17,
        name: "Fatimah KA",
        position: "Participants",
        image: "/images/id-card/fatimah KA.png",
        link: "#",
        CategoryTeam: { name: "Participants" },
    },
    {
        id: 18,
        name: "Feni Oktora",
        position: "Participants",
        image: "/images/id-card/feni oktora.png",
        link: "#",
        CategoryTeam: { name: "Participants" },
    },
    {
        id: 19,
        name: "Harits Alfi",
        position: "Participants",
        image: "/images/id-card/harits alfi.png",
        link: "#",
        CategoryTeam: { name: "Participants" },
    },
    {
        id: 20,
        name: "Jerry Selvia",
        position: "Participants",
        image: "/images/id-card/jerry selvia.png",
        link: "#",
        CategoryTeam: { name: "Participants" },
    },
    {
        id: 21,
        name: "Jumriah",
        position: "Participants",
        image: "/images/id-card/jumriah.png",
        link: "#",
        CategoryTeam: { name: "Participants" },
    },
    {
        id: 22,
        name: "Kak Jums",
        position: "Participants",
        image: "/images/id-card/kak jums.png",
        link: "#",
        CategoryTeam: { name: "Participants" },
    },
    {
        id: 23,
        name: "Naziah",
        position: "Participants",
        image: "/images/id-card/naziah.png",
        link: "#",
        CategoryTeam: { name: "Participants" },
    },
    {
        id: 24,
        name: "Nur Afiah",
        position: "Participants",
        image: "/images/id-card/nur afiah.png",
        link: "#",
        CategoryTeam: { name: "Participants" },
    },
    {
        id: 25,
        name: "Romawati",
        position: "Participants",
        image: "/images/id-card/romawati.png",
        link: "#",
        CategoryTeam: { name: "Participants" },
    },
    {
        id: 26,
        name: "Saniyyah",
        position: "Participants",
        image: "/images/id-card/saniyyah.png",
        link: "#",
        CategoryTeam: { name: "Participants" },
    },
    {
        id: 27,
        name: "Susi Salamah",
        position: "Participants",
        image: "/images/id-card/susi salamah.png",
        link: "#",
        CategoryTeam: { name: "Participants" },
    },
    {
        id: 28,
        name: "Syahidan Arief",
        position: "Participants",
        image: "/images/id-card/syahidan arief.png",
        link: "#",
        CategoryTeam: { name: "Participants" },
    },
    {
        id: 29,
        name: "Teguh Jati Purnama",
        position: "Participants",
        image: "/images/id-card/teguh jati purnama.png",
        link: "#",
        CategoryTeam: { name: "Participants" },
    },
    {
        id: 30,
        name: "Usamah Abdul Hakim",
        position: "Participants",
        image: "/images/id-card/usamah abdul hakim.png",
        link: "#",
        CategoryTeam: { name: "Participants" },
    },
    {
        id: 31,
        name: "Vidiandito",
        position: "Participants",
        image: "/images/id-card/vidiandito.png",
        link: "#",
        CategoryTeam: { name: "Participants" },
    },
    {
        id: 32,
        name: "Wahidah",
        position: "Participants",
        image: "/images/id-card/wahidah.png",
        link: "#",
        CategoryTeam: { name: "Participants" },
    },
    {
        id: 33,
        name: "Wahyu Ramadhan",
        position: "Participants",
        image: "/images/id-card/wahyu ramadhan.png",
        link: "#",
        CategoryTeam: { name: "Participants" },
    },
];

export default MentorCardContents;